# Content backend.
backend:
  name: github
  repo: spencels/bcc-site

# Uploads folder
media_folder: "imageuploads"

# The collections setting is the heart of your Netlify CMS configuration, as it
# determines how content types and editor fields in the UI generate files and
# content in your repository. Each collection you configure displays in the
# left sidebar of the Content page of the editor UI, in the order they are
# entered into config.yml.
collections:
  - name: pages
    label: Pages
    folder: ""
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

